In [3]:
#this program detects if an email is spam or not

In [1]:
#import libraries
import pandas as pd
import numpy as np
import string
import nltk
from nltk.corpus import stopwords

In [35]:
df = pd.read_csv('SPAM text message 20170820 - Data.csv')

In [36]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
df['Category'].replace(to_replace='spam',value='1',inplace=True)

In [38]:
df['Category'].replace(to_replace='ham',value='0',inplace=True)

In [39]:
df.head()

Category                                            Message
0        0  Go until jurong point, crazy.. Available only ...
1        0                      Ok lar... Joking wif u oni...
2        1  Free entry in 2 a wkly comp to win FA Cup fina...
3        0  U dun say so early hor... U c already then say...
4        0  Nah I don't think he goes to usf, he lives aro...

In [40]:
df.dtypes

Category    object
Message     object
dtype: object

In [46]:
df['Category'] = df['Category'].astype(int)

In [47]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [48]:
df.dtypes

Category     int32
Message     object
dtype: object

In [49]:
df.shape

(5572, 2)

In [50]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [51]:
df.drop_duplicates(inplace=True)
df.shape

(5157, 2)

In [54]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [55]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sufyan\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [59]:
def process_text(text):
    nopunc = [char for char in text if text is not string.punctuation]
    nopunc = ''.join(nopunc)
    
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    return clean_words
    
    

In [60]:
df['Message'].head().apply(process_text) 

0    [Go, jurong, point,, crazy.., Available, bugis...
1                 [Ok, lar..., Joking, wif, u, oni...]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3    [U, dun, say, early, hor..., U, c, already, sa...
4      [Nah, think, goes, usf,, lives, around, though]
Name: Message, dtype: object

In [67]:
message4 = 'hello hello world hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()
print(bow4.shape)

hello hello world hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


In [69]:
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['Message'])

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['Category'], test_size=0.20, random_state=42)

In [73]:
messages_bow.shape

(5157, 15328)

In [74]:
#naive bayes classifier

In [75]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,y_train)

In [76]:
print(classifier.predict(X_train))

[0 0 0 ... 0 0 0]


In [77]:
print(y_train.values)

[0 0 0 ... 0 0 0]


In [80]:
from sklearn.metrics import classification_report , confusion_matrix ,accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train,pred))
print()
print('confusion_matrix \n', confusion_matrix(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3620
           1       0.99      0.98      0.99       505

    accuracy                           1.00      4125
   macro avg       1.00      0.99      0.99      4125
weighted avg       1.00      1.00      1.00      4125


confusion_matrix 
 [[3617    3]
 [   9  496]]


In [81]:
print('accuracy',accuracy_score(y_train,pred))

accuracy 0.9970909090909091


In [83]:
print(classifier.predict(X_test))
print(y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [87]:
from sklearn.metrics import classification_report , confusion_matrix ,accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('confusion_matrix \n', confusion_matrix(y_test,pred))
print()
print('accuracy',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      0.95      0.97       896
           1       0.74      0.96      0.84       136

    accuracy                           0.95      1032
   macro avg       0.87      0.96      0.90      1032
weighted avg       0.96      0.95      0.95      1032


confusion_matrix 
 [[850  46]
 [  5 131]]

accuracy 0.9505813953488372
